workflows:
  kivy-android:
    name: Kivy Android Build
    max_build_duration: 120
    environment:
      vars:
        PYTHON_VERSION: "3.10"
    scripts:
      - name: Installer les dépendances
        script: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install --upgrade pip
          pip install buildozer cython virtualenv
      - name: Préparer l’environnement
        script: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Compiler l’APK
        script: |
          buildozer android debug
    artifacts:
      - build/*.apk
