workflows:
  kivy-android:
    name: Build Kivy Android App
    environment:
      vars:
        BUILD_DIR: $CM_BUILD_DIR
        PYTHON_VERSION: 3.10  # Spécifiez Python 3.10
    scripts:
      - name: Installer les dépendances Python
        script: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-venv python3-distutils
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer==1.4.0 cython virtualenv
          pip install python3-distutils
          buildozer android debug

      - name: Construire l'APK avec Buildozer
        script: |
          export PATH=$HOME/.local/bin:$PATH
          source venv/bin/activate
          buildozer android debug

    artifacts:
      - build/*.apk
