workflows:
  kivy-android:
    name: Kivy Android Build
    max_build_duration: 120
    environment:
      vars:
        PYTHON_VERSION: "3.10.12"
      flutter: stable

    scripts:
      - name: Installer les dépendances
        script: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv openjdk-11-jdk wget unzip
          pip install --upgrade pip
          pyenv global $PYTHON_VERSION
          python -m ensurepip
          pip install setuptools
          python --version
          pip install buildozer cython virtualenv

      - name: Installer Android SDK
        script: |
          # Télécharger et installer l'Android SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip -d $HOME/Android
          export ANDROID_HOME=$HOME/Android
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          echo "ANDROID_HOME=$ANDROID_HOME" >> ~/.bashrc
          echo "export PATH=$PATH" >> ~/.bashrc
          source ~/.bashrc

      - name: Accepter les licences Android SDK
        script: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Préparer l’environnement
        script: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade buildozer

      - name: Compiler l’APK
        script: |
          source venv/bin/activate
          buildozer android debug

    artifacts:
      - build/*.apk
