workflows:
  kivy-android:
    name: Kivy Android Build
    max_build_duration: 120
    environment:
      vars:
        PYTHON_VERSION: "3.10.12"
      flutter: stable

    scripts:
      - name: Installer les dépendances
        script: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv openjdk-11-jdk wget unzip
          pip install --upgrade pip
          pyenv global $PYTHON_VERSION
          python -m ensurepip
          pip install setuptools
          python --version
          pip install buildozer cython virtualenv

      - name: Installer Android SDK
        script: |
          # Créer un répertoire pour le SDK Android
          mkdir -p $HOME/Android

          # Télécharger le SDK Android Command-Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -P $HOME/Android
          unzip $HOME/Android/commandlinetools-linux-7302050_latest.zip -d $HOME/Android/cmdline-tools

          # Vérifier si le SDK a été correctement installé
          ls $HOME/Android/cmdline-tools

          # Mettre à jour les variables d'environnement
          export ANDROID_HOME=$HOME/Android
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          # Vérifier que sdkmanager est maintenant accessible
          echo $PATH
          sdkmanager --version

      - name: Accepter les licences Android SDK
        script: |
          # Vérifier si sdkmanager est bien installé
          if ! command -v sdkmanager &>/dev/null; then
            echo "sdkmanager command not found!"
            exit 1
          fi
          
          # Accepter les licences
          yes | sdkmanager --licenses

          # Télécharger les outils nécessaires
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Préparer l’environnement
        script: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade buildozer

      - name: Compiler l’APK
        script: |
          source venv/bin/activate
          buildozer android debug

    artifacts:
      - build/*.apk
